### ISSUE TITLE
Images Upside Down

### ISSUE THREAD

**Issue by MikeTho16** [openstreetview/openstreetview.org#14]
For example: 
[http://openstreetview.org/details/6040/366](url)
Recommend  that image orientation be detected from metadata if possible and rotated accordingly upon upload and an option be placed on website to rotate images.

**Comment by ToeBee** [comment]
I'm pretty sure they do correctly read the EXIF orientation metadata from pictures. The following sequence was captured while my GoPro camera was misconfigured so all the pictures were upside down. I manually changed the EXIF orientation tag using exiftool before uploading and it appears correctly on the website:
http://openstreetview.com/details/10925/4

Was yours captured with an external camera or the phone app? I've had my phone just flip its orientation in mid-capture before. Probably the result of a bump or something. I suspect these pictures were just tagged wrong because of the phone's hardware.

**Comment by MikeTho16** [comment]
@ToeBee Toby, I should have been more precise in my original reporting.  The images were not collected by me. I was assuming they were collected with either the Android or iOS apps, but you very well be correct that they were collected with some other device and the EXIF data was simply wrong.  @martijnv-telenav is there anyway you could contact the contributor (JeremyMa) and ask what the collection platform was, or perhaps OpenStreetView has additional metadata that could shed light on the issue? In any event, perhaps someone with the necessary rights could go into the service and rotate these images.  (I know the user who contributed the photos has that ability, but perhaps an admin does as well). It is amazingly difficult to map looking at an image that is upside down!

**Comment by mvexel** [comment]
I can try sending him a message through OSM messaging -- that's the only way we have to get in touch if they did not leave their email when signing up.

**Comment by mvexel** [comment]
Sent them a message through OSM

**Comment by martijnv-telenav** [comment]
Did not hear back, closing this now but if someone else has this problem feel free to reopen.
