### ISSUE TITLE
JOSM Plugin Does Not Load

### ISSUE THREAD

**Issue by MikeTho16** [openstreetview/openstreetview.org#24]
System Info:
Ubuntu 14.04 LTS
JOSM: 10526
Java: 1.7.0_101

Actions performed:
Edit -> Preferences -> Plugins -> OpenStreetView 13 -> Update Plugins

Behavior expected:
Some new menu item(s) that will allow me to access OpenStreetView images from within JOSM or something in the images preferences dialog.

Behavior encountered:
No new menu items or functionality evident.  
Returning to the plugins dialog a second time shows that OpenStreetView is not checked (indicating that it is not installed), but checking it and clicking "update plugins" produces a message "all installed plugins are up to date. JOSM does not have to download newer versions."

**Comment by beataj-telenav** [comment]
Thanks for reporting the issue.  We have installed the plugin on Ubuntu without any issue.

In order to install the plugin you need to perform the following actions:
   1. go to Edit -> Preferences ->Plugins -> OpenStreetView
   2. select manually the checkbox displayed before the OpenStreetView icon
   3. click on "Update plugins" button
   4. click on "OK" button
 After performing these steps JOSM should restart and the OpenStreetView layer and right panel window should be visible.

**Comment by MikeTho16** [comment]
I finally got the plugin to load.  It took several attempts.  I am going to do some more testing, but I am not sure it is working correctly.
